- name: play-1
  hosts: localhost
  tasks:
  - name: play-1 and task-1
    ansible.builtin.debug:
      msg: "Hello i am play-1 and task-1"


- name: play-2
  hosts: localhost
  tasks:
  - name: play-2 and task-1
    ansible.builtin.debug:
      msg: "Hello I am play-2 and task-1"