172.31.24.220

[web]
172.31.18.61

[web:vars]
DB_URL="http://db.vinaydevops.online"

[localhost]
localhost

[localhost:vars]
Course="Devops with aws"
Trainer="Vinay"
Duration="120hrs"
WISHES="Morning from inventory"

[db]
172.31.24.222

[app]
172.31.24.223

[all:children]
web
db
app

